registry:
  restart: always
  image: registry:2
  ports:
    - 5000:5000
  environment:
    REGISTRY_HTTP_TLS_CERTIFICATE: /certs/registry_auth.crt
    REGISTRY_HTTP_TLS_KEY: /certs/registry_auth.key
    REGISTRY_AUTH: htpasswd
    REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
    REGISTRY_AUTH_HTPASSWD_REALM: coopertennis 
  volumes:
    - /Users/gkidiyoor/apigee/git/docker-registry-auth-push/registrydata:/var/lib/registry
    - /Users/gkidiyoor/apigee/git/docker-registry-auth-push/certs:/certs
    - /Users/gkidiyoor/apigee/git/docker-registry-auth-push/auth:/auth
